name: node

on:
  push:
    tags-ignore:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    container: 'node:18-slim'
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run lint
  build:
    name: Build
    runs-on: ubuntu-latest
    container: 'node:18-slim'
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build
